### ISSUE TITLE
Flat View renders to only 2/3s of the screen on the right in tablet landscape orientation

### ISSUE THREAD

**Issue by RichSharpe** [unplugged/unplugged-controls#38]
Opening a Flat View with no View List Control on an iPad shows the list aligned to the right with a large empty gap on the left.

**Comment by whitemx** [comment]
This would be resolved by adding a custom.css to the application to re-format the layout of the view column to be left aligned.

``` css
@media screen and (min-width: 1001px) {
    .pullleft {
        margin-left: -40% !important;
    }
}
```

and wrapping the view with a div with .pullleft assigned as the class.

``` xml
<div class="pullleft">
    <xc:unpFlatView insetData="false" numberofrows="999"
        refreshmethod="none"
        categoryfilter="#{javascript:document1.getDocument().getUniversalID()}"
        detailColumn="Date" summaryColumn="Topic" title="Responses"
        viewName="(UnpResponses)" xpageDoc="Response.xsp">
    </xc:unpFlatView>
</div>
```
